### ISSUE TITLE
extrinsic_cal: missing license

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_calibration#11]
Source files contain the Apache 2.0 license headers, but the manifest doesn't contain that information.

**Comment by drchrislewis** [comment]
<license>Apache</license> is in the package.xml

**Comment by gavanderhoorn** [comment]
Yes, that was fixed in 6d46b9e3, which was merged in #15, two weeks after this issue was opened.

**Comment by VictorLamoine** [comment]
@drchrislewis This can be closed, every `package.xml` contains the Apache 2.0 license tag.
