### ISSUE TITLE
extrinsic_cal: CERES_INCLUDE_DIRS never added to include path

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_calibration#13]
Not sure this is a problem, but even though the Ceres library is `find_package(  REQUIRED)`-ed, the contents of the `CERES_INCLUDE_DIRS` variable is never appended to the include path in `CMakeLists.txt`:
```
include_directories(include
  ${catkin_INCLUDE_DIRS} ${EIGEN_INCLUDE_DIRS}
)
```

It is also not added to the `INCLUDE_DIRS` argument of `catkin_package(..)`, but that could be intentional.

**Comment by VictorLamoine** [comment]
@drchrislewis This issue is [fixed](https://github.com/ros-industrial/industrial_calibration/search?utf8=%E2%9C%93&q=CERES_INCLUDE_DIRS) and can be closed.
