### ISSUE TITLE
extrinsic_cal: missing find_package() for yaml-cpp

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_calibration#14]
The `yaml-cpp` library is added as a linking dependency in:
```
target_link_libraries(industrial_extrinsic_cal_ceres
  yaml-cpp ${catkin_LIBRARIES})
```
without first a `find_package()`.

ROS depends on it as well, so it will probably always be present when `industrial_calibration` is build, but it might be a good idea to `find_package()` it.

**Comment by VictorLamoine** [comment]
@drchrislewis This (and #50) can be closed as #62 fixed this issue, [here](https://github.com/ros-industrial/industrial_calibration/blob/indigo-devel/rgbd_depth_correction/CMakeLists.txt#L29) and [here](https://github.com/ros-industrial/industrial_calibration/blob/indigo-devel/industrial_extrinsic_cal/CMakeLists.txt#L32).
