### ISSUE TITLE
Automated created of Target yaml file(s)

### ISSUE THREAD

**Issue by gomezc** [ros-industrial/industrial_calibration#18]
Right now the point's are entered manually into the target.yaml file and when the number of points are as high as 121, it would be better if we had a target.yaml exporter of some sort. The target.yaml exporter/creator should take in a few inputs and output the target.yaml file correctly formatted and with all necessary parameters including all points.

**Comment by drchrislewis** [comment]
there is now a generate_target.m under the targets directory in extrinsic calibration which generates the points as well as defaults for other elements
