### ISSUE TITLE
Merge calibration node and calibration service node

### ISSUE THREAD

**Issue by gomezc** [ros-industrial/industrial_calibration#19]
They (industrial_extrinsic_cal/src/test_cal_job.cpp and industrial_extrinsic_cal/src/calibration_service.cpp) hold nearly identical code. A single calibration node should be capable of handing both modes of operation.

**Comment by drchrislewis** [comment]
several old executables like this are not moved to the old directory and removed from the cmake. We keep them only to recover old lab demonstrations. At this point I believe the old directory can be deleted.
