### ISSUE TITLE
Mutable joint state publisher parameter doesn't follow naming convention

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/industrial_calibration#36]
The mutable joint state publisher loads the yaml file name from a parameter `mutableJointStateYamlFile` that doesn't follow the naming convention, `lower_case`.  See [here](https://github.com/ros-industrial/industrial_calibration/blob/hydro-devel/industrial_extrinsic_cal/src/nodes/mutable_joint_state_publisher.cpp#L33)

The parameter name should be corrected in a backwards compatible way that issues a warning if the old name is used, but still works.

**Comment by drchrislewis** [comment]
next pull should fix,
