### ISSUE TITLE
Default branch: indigo-devel

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/industrial_calibration#77]
I think `indigo-devel` should be the default branch; it is more up-to-date and contains bug/compilation fixes.

**Comment by drchrislewis** [comment]
@VictorLamoine Can you give tell me how to promote one branch to be the default?

**Comment by VictorLamoine** [comment]
Yes:
https://help.github.com/articles/setting-the-default-branch/

**Comment by drchrislewis** [comment]
@VictorLamoine done by Shaun
